import { defineConfig } from '@wagmi/cli';
import { actions } from '@wagmi/cli/plugins';

export default defineConfig({
  out: 'src/generated/abi/index.ts',
  contracts: [
    {
      name: 'TrailblazersBadges',
      address: {
        167000: '0xa20a8856e00F5ad024a55A663F06DCc419FFc4d5',
        167009: '0x010992985d1DA35676271bd5abA16E0E8D5582d3',
      },
      abi: [
        {
          type: 'function',
          name: 'BADGE_ANDROIDS',
          inputs: [],
          outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'BADGE_BOUNCERS',
          inputs: [],
          outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'BADGE_DRUMMERS',
          inputs: [],
          outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'BADGE_MASTERS',
          inputs: [],
          outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'BADGE_MONKS',
          inputs: [],
          outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'BADGE_RAVERS',
          inputs: [],
          outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'BADGE_ROBOTS',
          inputs: [],
          outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'BADGE_SHINTO',
          inputs: [],
          outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'MOVEMENT_BASED',
          inputs: [],
          outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'MOVEMENT_BOOSTED',
          inputs: [],
          outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'MOVEMENT_NEUTRAL',
          inputs: [],
          outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'UPGRADE_INTERFACE_VERSION',
          inputs: [],
          outputs: [{ name: '', type: 'string', internalType: 'string' }],
          stateMutability: 'view',
        },
        { type: 'function', name: 'acceptOwnership', inputs: [], outputs: [], stateMutability: 'nonpayable' },
        {
          type: 'function',
          name: 'approve',
          inputs: [
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
          ],
          outputs: [],
          stateMutability: 'nonpayable',
        },
        {
          type: 'function',
          name: 'badgeBalances',
          inputs: [{ name: '_owner', type: 'address', internalType: 'address' }],
          outputs: [{ name: '', type: 'bool[]', internalType: 'bool[]' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'badges',
          inputs: [{ name: '_tokenId', type: 'uint256', internalType: 'uint256' }],
          outputs: [{ name: '_badgeId', type: 'uint256', internalType: 'uint256' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'balanceOf',
          inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
          outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'blacklist',
          inputs: [],
          outputs: [{ name: '', type: 'address', internalType: 'contract IMinimalBlacklist' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'canMint',
          inputs: [
            { name: '_signature', type: 'bytes', internalType: 'bytes' },
            { name: '_minter', type: 'address', internalType: 'address' },
            { name: '_tokenId', type: 'uint256', internalType: 'uint256' },
          ],
          outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'getApproved',
          inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
          outputs: [{ name: '', type: 'address', internalType: 'address' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'getHash',
          inputs: [
            { name: '_minter', type: 'address', internalType: 'address' },
            { name: '_tokenId', type: 'uint256', internalType: 'uint256' },
          ],
          outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
          stateMutability: 'pure',
        },
        {
          type: 'function',
          name: 'getTokenId',
          inputs: [
            { name: '_user', type: 'address', internalType: 'address' },
            { name: '_badgeId', type: 'uint256', internalType: 'uint256' },
          ],
          outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'initialize',
          inputs: [
            { name: '_owner', type: 'address', internalType: 'address' },
            { name: '_rootURI', type: 'string', internalType: 'string' },
            { name: '_mintSigner', type: 'address', internalType: 'address' },
            { name: '_blacklistAddress', type: 'address', internalType: 'contract IMinimalBlacklist' },
          ],
          outputs: [],
          stateMutability: 'nonpayable',
        },
        {
          type: 'function',
          name: 'initialize',
          inputs: [
            { name: '_owner', type: 'address', internalType: 'address' },
            { name: '_mintSigner', type: 'address', internalType: 'address' },
            { name: '_blacklist', type: 'address', internalType: 'contract IMinimalBlacklist' },
          ],
          outputs: [],
          stateMutability: 'nonpayable',
        },
        {
          type: 'function',
          name: 'isApprovedForAll',
          inputs: [
            { name: 'owner', type: 'address', internalType: 'address' },
            { name: 'operator', type: 'address', internalType: 'address' },
          ],
          outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'mint',
          inputs: [
            { name: '_signature', type: 'bytes', internalType: 'bytes' },
            { name: '_badgeId', type: 'uint256', internalType: 'uint256' },
          ],
          outputs: [],
          stateMutability: 'nonpayable',
        },
        {
          type: 'function',
          name: 'mint',
          inputs: [
            { name: '_signature', type: 'bytes', internalType: 'bytes' },
            { name: '_minter', type: 'address', internalType: 'address' },
            { name: '_badgeId', type: 'uint256', internalType: 'uint256' },
          ],
          outputs: [],
          stateMutability: 'nonpayable',
        },
        {
          type: 'function',
          name: 'mintSigner',
          inputs: [],
          outputs: [{ name: '', type: 'address', internalType: 'address' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'minted',
          inputs: [{ name: 'signatureHash', type: 'bytes32', internalType: 'bytes32' }],
          outputs: [{ name: 'hasMinted', type: 'bool', internalType: 'bool' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'movementBadges',
          inputs: [
            { name: 'movementBadgeHash', type: 'bytes32', internalType: 'bytes32' },
            { name: '', type: 'uint256', internalType: 'uint256' },
          ],
          outputs: [{ name: 'movementBadge', type: 'uint256', internalType: 'uint256' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'movements',
          inputs: [{ name: '_user', type: 'address', internalType: 'address' }],
          outputs: [{ name: '_movement', type: 'uint256', internalType: 'uint256' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'name',
          inputs: [],
          outputs: [{ name: '', type: 'string', internalType: 'string' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'owner',
          inputs: [],
          outputs: [{ name: '', type: 'address', internalType: 'address' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'ownerOf',
          inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
          outputs: [{ name: '', type: 'address', internalType: 'address' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'pendingOwner',
          inputs: [],
          outputs: [{ name: '', type: 'address', internalType: 'address' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'proxiableUUID',
          inputs: [],
          outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
          stateMutability: 'view',
        },
        { type: 'function', name: 'renounceOwnership', inputs: [], outputs: [], stateMutability: 'nonpayable' },
        {
          type: 'function',
          name: 'safeTransferFrom',
          inputs: [
            { name: 'from', type: 'address', internalType: 'address' },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
          ],
          outputs: [],
          stateMutability: 'nonpayable',
        },
        {
          type: 'function',
          name: 'safeTransferFrom',
          inputs: [
            { name: 'from', type: 'address', internalType: 'address' },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
            { name: 'data', type: 'bytes', internalType: 'bytes' },
          ],
          outputs: [],
          stateMutability: 'nonpayable',
        },
        {
          type: 'function',
          name: 'setApprovalForAll',
          inputs: [
            { name: 'operator', type: 'address', internalType: 'address' },
            { name: 'approved', type: 'bool', internalType: 'bool' },
          ],
          outputs: [],
          stateMutability: 'nonpayable',
        },
        {
          type: 'function',
          name: 'setMovement',
          inputs: [{ name: '_movementId', type: 'uint256', internalType: 'uint256' }],
          outputs: [],
          stateMutability: 'nonpayable',
        },
        {
          type: 'function',
          name: 'setMovement',
          inputs: [
            { name: '_user', type: 'address', internalType: 'address' },
            { name: '_movementId', type: 'uint256', internalType: 'uint256' },
          ],
          outputs: [],
          stateMutability: 'nonpayable',
        },
        {
          type: 'function',
          name: 'setUri',
          inputs: [{ name: '_uri', type: 'string', internalType: 'string' }],
          outputs: [],
          stateMutability: 'nonpayable',
        },
        {
          type: 'function',
          name: 'supportsInterface',
          inputs: [{ name: 'interfaceId', type: 'bytes4', internalType: 'bytes4' }],
          outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'symbol',
          inputs: [],
          outputs: [{ name: '', type: 'string', internalType: 'string' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'tokenByIndex',
          inputs: [{ name: 'index', type: 'uint256', internalType: 'uint256' }],
          outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'tokenOfOwnerByIndex',
          inputs: [
            { name: 'owner', type: 'address', internalType: 'address' },
            { name: 'index', type: 'uint256', internalType: 'uint256' },
          ],
          outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'tokenURI',
          inputs: [{ name: '_tokenId', type: 'uint256', internalType: 'uint256' }],
          outputs: [{ name: '', type: 'string', internalType: 'string' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'totalSupply',
          inputs: [],
          outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
          stateMutability: 'view',
        },
        {
          type: 'function',
          name: 'transferFrom',
          inputs: [
            { name: 'from', type: 'address', internalType: 'address' },
            { name: 'to', type: 'address', internalType: 'address' },
            { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
          ],
          outputs: [],
          stateMutability: 'nonpayable',
        },
        {
          type: 'function',
          name: 'transferOwnership',
          inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
          outputs: [],
          stateMutability: 'nonpayable',
        },
        {
          type: 'function',
          name: 'updateBlacklist',
          inputs: [{ name: '_blacklist', type: 'address', internalType: 'contract IMinimalBlacklist' }],
          outputs: [],
          stateMutability: 'nonpayable',
        },
        {
          type: 'function',
          name: 'updateMintSigner',
          inputs: [{ name: '_mintSigner', type: 'address', internalType: 'address' }],
          outputs: [],
          stateMutability: 'nonpayable',
        },
        {
          type: 'function',
          name: 'upgradeToAndCall',
          inputs: [
            { name: 'newImplementation', type: 'address', internalType: 'address' },
            { name: 'data', type: 'bytes', internalType: 'bytes' },
          ],
          outputs: [],
          stateMutability: 'payable',
        },
        {
          type: 'function',
          name: 'userBadges',
          inputs: [
            { name: '_user', type: 'address', internalType: 'address' },
            { name: '_badgeId', type: 'uint256', internalType: 'uint256' },
          ],
          outputs: [{ name: '_tokenId', type: 'uint256', internalType: 'uint256' }],
          stateMutability: 'view',
        },
        {
          type: 'event',
          name: 'Approval',
          inputs: [
            { name: 'owner', type: 'address', indexed: true, internalType: 'address' },
            { name: 'approved', type: 'address', indexed: true, internalType: 'address' },
            { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
          ],
          anonymous: false,
        },
        {
          type: 'event',
          name: 'ApprovalForAll',
          inputs: [
            { name: 'owner', type: 'address', indexed: true, internalType: 'address' },
            { name: 'operator', type: 'address', indexed: true, internalType: 'address' },
            { name: 'approved', type: 'bool', indexed: false, internalType: 'bool' },
          ],
          anonymous: false,
        },
        {
          type: 'event',
          name: 'BadgeCreated',
          inputs: [
            { name: '_tokenId', type: 'uint256', indexed: false, internalType: 'uint256' },
            { name: '_minter', type: 'address', indexed: false, internalType: 'address' },
            { name: '_badgeId', type: 'uint256', indexed: false, internalType: 'uint256' },
          ],
          anonymous: false,
        },
        {
          type: 'event',
          name: 'BlacklistUpdated',
          inputs: [{ name: '_blacklist', type: 'address', indexed: false, internalType: 'address' }],
          anonymous: false,
        },
        {
          type: 'event',
          name: 'Initialized',
          inputs: [{ name: 'version', type: 'uint64', indexed: false, internalType: 'uint64' }],
          anonymous: false,
        },
        {
          type: 'event',
          name: 'MintConsumed',
          inputs: [
            { name: '_minter', type: 'address', indexed: false, internalType: 'address' },
            { name: '_tokenId', type: 'uint256', indexed: false, internalType: 'uint256' },
          ],
          anonymous: false,
        },
        {
          type: 'event',
          name: 'MintSignerUpdated',
          inputs: [{ name: '_mintSigner', type: 'address', indexed: false, internalType: 'address' }],
          anonymous: false,
        },
        {
          type: 'event',
          name: 'MovementSet',
          inputs: [
            { name: '_user', type: 'address', indexed: false, internalType: 'address' },
            { name: '_movementId', type: 'uint256', indexed: false, internalType: 'uint256' },
          ],
          anonymous: false,
        },
        {
          type: 'event',
          name: 'OwnershipTransferStarted',
          inputs: [
            { name: 'previousOwner', type: 'address', indexed: true, internalType: 'address' },
            { name: 'newOwner', type: 'address', indexed: true, internalType: 'address' },
          ],
          anonymous: false,
        },
        {
          type: 'event',
          name: 'OwnershipTransferred',
          inputs: [
            { name: 'previousOwner', type: 'address', indexed: true, internalType: 'address' },
            { name: 'newOwner', type: 'address', indexed: true, internalType: 'address' },
          ],
          anonymous: false,
        },
        {
          type: 'event',
          name: 'Transfer',
          inputs: [
            { name: 'from', type: 'address', indexed: true, internalType: 'address' },
            { name: 'to', type: 'address', indexed: true, internalType: 'address' },
            { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
          ],
          anonymous: false,
        },
        {
          type: 'event',
          name: 'Upgraded',
          inputs: [{ name: 'implementation', type: 'address', indexed: true, internalType: 'address' }],
          anonymous: false,
        },
        {
          type: 'event',
          name: 'UriSet',
          inputs: [{ name: '_uri', type: 'string', indexed: false, internalType: 'string' }],
          anonymous: false,
        },
        { type: 'error', name: 'ADDRESS_BLACKLISTED', inputs: [] },
        {
          type: 'error',
          name: 'AddressEmptyCode',
          inputs: [{ name: 'target', type: 'address', internalType: 'address' }],
        },
        {
          type: 'error',
          name: 'ERC1967InvalidImplementation',
          inputs: [{ name: 'implementation', type: 'address', internalType: 'address' }],
        },
        { type: 'error', name: 'ERC1967NonPayable', inputs: [] },
        { type: 'error', name: 'ERC721EnumerableForbiddenBatchMint', inputs: [] },
        {
          type: 'error',
          name: 'ERC721IncorrectOwner',
          inputs: [
            { name: 'sender', type: 'address', internalType: 'address' },
            { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
            { name: 'owner', type: 'address', internalType: 'address' },
          ],
        },
        {
          type: 'error',
          name: 'ERC721InsufficientApproval',
          inputs: [
            { name: 'operator', type: 'address', internalType: 'address' },
            { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
          ],
        },
        {
          type: 'error',
          name: 'ERC721InvalidApprover',
          inputs: [{ name: 'approver', type: 'address', internalType: 'address' }],
        },
        {
          type: 'error',
          name: 'ERC721InvalidOperator',
          inputs: [{ name: 'operator', type: 'address', internalType: 'address' }],
        },
        {
          type: 'error',
          name: 'ERC721InvalidOwner',
          inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
        },
        {
          type: 'error',
          name: 'ERC721InvalidReceiver',
          inputs: [{ name: 'receiver', type: 'address', internalType: 'address' }],
        },
        {
          type: 'error',
          name: 'ERC721InvalidSender',
          inputs: [{ name: 'sender', type: 'address', internalType: 'address' }],
        },
        {
          type: 'error',
          name: 'ERC721NonexistentToken',
          inputs: [{ name: 'tokenId', type: 'uint256', internalType: 'uint256' }],
        },
        {
          type: 'error',
          name: 'ERC721OutOfBoundsIndex',
          inputs: [
            { name: 'owner', type: 'address', internalType: 'address' },
            { name: 'index', type: 'uint256', internalType: 'uint256' },
          ],
        },
        { type: 'error', name: 'FailedInnerCall', inputs: [] },
        { type: 'error', name: 'INVALID_BADGE_ID', inputs: [] },
        { type: 'error', name: 'INVALID_INPUT', inputs: [] },
        { type: 'error', name: 'INVALID_MOVEMENT_ID', inputs: [] },
        { type: 'error', name: 'InvalidInitialization', inputs: [] },
        { type: 'error', name: 'MINTER_NOT_WHITELISTED', inputs: [] },
        { type: 'error', name: 'MINTS_EXCEEDED', inputs: [] },
        { type: 'error', name: 'NotInitializing', inputs: [] },
        { type: 'error', name: 'ONLY_MINT_SIGNER', inputs: [] },
        {
          type: 'error',
          name: 'OwnableInvalidOwner',
          inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
        },
        {
          type: 'error',
          name: 'OwnableUnauthorizedAccount',
          inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
        },
        { type: 'error', name: 'UUPSUnauthorizedCallContext', inputs: [] },
        {
          type: 'error',
          name: 'UUPSUnsupportedProxiableUUID',
          inputs: [{ name: 'slot', type: 'bytes32', internalType: 'bytes32' }],
        },
      ],
    },
    {
      name: 'ClaimGalxePoints',
      address: {
        167000: '0xD68BF51E2d73A7c7D023f1fd58e2F66F602A8088',
      },
      abi: [
        {
          type: 'function',
          name: 'alreadyRegistered',
          inputs: [{ name: '', type: 'address', internalType: 'address' }],
          outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
          stateMutability: 'view',
        },
        { type: 'function', name: 'register', inputs: [], outputs: [], stateMutability: 'nonpayable' },
        {
          type: 'event',
          name: 'Registered',
          inputs: [{ name: 'registrant', type: 'address', indexed: false, internalType: 'address' }],
          anonymous: false,
        },
      ],
    },
  ],
  plugins: [actions()],
});
