export const levelTiers: { percentileCap: number; level: string; title: string }[] = [
  { percentileCap: 50, level: '0', title: 'Beginner' },
  { percentileCap: 58, level: '1', title: 'Initiate' },
  { percentileCap: 66, level: '2', title: 'Senshi I' },
  { percentileCap: 74, level: '3', title: 'Senshi II' },
  { percentileCap: 82, level: '4', title: 'Samurai I' },
  { percentileCap: 90, level: '5', title: 'Samurai II' },
  { percentileCap: 92, level: '6', title: 'Sensei I' },
  { percentileCap: 94, level: '7', title: 'Sensei II' },
  { percentileCap: 96, level: '8', title: 'Taichou I' },
  { percentileCap: 98, level: '9', title: 'Taichou II' },
  { percentileCap: 99, level: '10', title: 'Shogun' },
  { percentileCap: 99.5, level: '11', title: 'Hashira' },
  { percentileCap: 99.9, level: '12', title: 'Kodai' },
  { percentileCap: 99.99, level: '13', title: 'Densetsu' },
  { percentileCap: 100, level: '14', title: 'Legend' },
];
