name: Sync Folder to GCS Bucket

on:
  push:
    branches:
      - main # Run the action when there is a push to the main branch
  workflow_dispatch: # Allow the action to be triggered manually

jobs:
  sync:
    name: Sync Files to GCS
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Authenticate to Google Cloud
        run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Sync Folder to GCS Bucket
        run: |
          gsutil rsync -r ./static gs://trailblazer-cdn
