name: UI - Build and Checks

on: workflow_call

jobs:
  Build-and-checks:
    runs-on: [taiko-runner]
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: Build Svelte app
        working-directory: .
        run: pnpm build

      - name: Svelte check
        working-directory: .
        run: pnpm svelte:check

      - name: Linting
        working-directory: .
        run: pnpm lint

      - name: Unit tests
        working-directory: .
        run: pnpm test:unit
