env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets. VERCEL_PROJECT_ID_TRAILBLAZER }}

on:
  push:
    branches:
      - 'main'

jobs:
  Deploy-Production:
    runs-on: [taiko-runner]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: Install Vercel CLI
        run: pnpm add --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Set Vercel Environment Variables
        run: |
          vercel env add PUBLIC_TRAILBLAZER_API_URL production $PUBLIC_TRAILBLAZER_API_URL --token=${{ secrets.VERCEL_TOKEN }}
          vercel env add PUBLIC_WALLETCONNECT_PROJECT_ID production $PUBLIC_WALLETCONNECT_PROJECT_ID --token=${{ secrets.VERCEL_TOKEN }}
          # Add more variables as needed

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
